source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

workspace 'BLE_TEST'

workspace 'BLE_TEST'
target 'BLE_TEST' do
xcodeproj 'BLE_TEST.xcodeproj'
pod 'AFNetworking', '~> 3.0'
pod 'Alamofire', '~> 4.3'
end
