source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

workspace 'blesample'

target 'blesample' do

xcodeproj 'blesample.xcodeproj'
workspace 'blesample'
pod 'AFNetworking', '~> 3.0'
pod 'UIToast'
pod 'Alamofire', '~> 4.3'
pod 'MBProgressHUD', '~> 1.0.0'
pod 'iOSDFULibrary', '~> 3.0'
end